version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: mongod --bind_ip_all
  
  mysql:
    image: mysql:latest
    container_name: ingredients
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mdp
      MYSQL_DATABASE: raw_ingredients
      MYSQL_USER: api_endpoint
      MYSQL_PASSWORD: abracadabra
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  api:
    build: .
    container_name: api_container
    ports:
      - "80:80"
    depends_on:
      - mongo
      - mysql
    environment:
      - MONGO_URI=mongodb://mongo:27017